-- PEMS schema for PostgreSQL 16 (target: corpappdb, schema "pems").
-- Consolidated equivalent of the MySQL migrations 001–012 (all ALTERs folded in),
-- ported to Postgres: NUMERIC for DECIMAL, BOOLEAN for TINYINT(1), TIMESTAMP for
-- DATETIME, JSONB for JSON, IDENTITY for AUTO_INCREMENT, and an updated_at trigger
-- in place of MySQL's "ON UPDATE CURRENT_TIMESTAMP".
--
-- The raw meter table pems.em_valuedata_ci1001 is synced externally and already
-- present — this file never touches it. Run once against corpappdb as a role that
-- can create objects in schema "pems".

SET search_path TO pems;

-- updated_at auto-touch (replaces MySQL's ON UPDATE CURRENT_TIMESTAMP) -----------
CREATE OR REPLACE FUNCTION pems.set_updated_at() RETURNS trigger AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

-- =========================================================================
-- MASTER DATA
-- =========================================================================
CREATE TABLE IF NOT EXISTS pems_cost_center (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sap_costcenter  VARCHAR(20)  NOT NULL UNIQUE,
    description     VARCHAR(100) NOT NULL,
    category        VARCHAR(40),
    is_active       BOOLEAN      NOT NULL DEFAULT true,
    created_at      TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pems_meter (
    device_id       VARCHAR(6)  NOT NULL,
    feeder_id       SMALLINT    NOT NULL,
    client_id       VARCHAR(6)  NOT NULL DEFAULT 'CI1001',
    plant_id        VARCHAR(6)  NOT NULL DEFAULT 'PI1001',
    device_name     VARCHAR(50),
    feeder_name     VARCHAR(80),
    feeder_location VARCHAR(40),
    parent_feeder   VARCHAR(80),
    sld_costcenter  VARCHAR(20),
    section         VARCHAR(40),
    role            VARCHAR(15)  NOT NULL DEFAULT 'unknown',
    is_incomer      BOOLEAN      NOT NULL DEFAULT false,
    is_enabled      BOOLEAN      NOT NULL DEFAULT true,
    is_virtual      BOOLEAN      NOT NULL DEFAULT false,
    display_order   INT,
    is_active       BOOLEAN      NOT NULL DEFAULT true,
    synced_at       TIMESTAMP,
    PRIMARY KEY (device_id, feeder_id)
);

CREATE TABLE IF NOT EXISTS pems_load (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    load_code       VARCHAR(30)  NOT NULL UNIQUE,
    load_name       VARCHAR(80)  NOT NULL,
    sap_costcenter  VARCHAR(20),
    section         VARCHAR(40),
    load_type       VARCHAR(20)  NOT NULL DEFAULT 'aux',
    is_derived      BOOLEAN      NOT NULL DEFAULT false,
    display_order   INT,
    is_active       BOOLEAN      NOT NULL DEFAULT true,
    created_at      TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT fk_load_cc FOREIGN KEY (sap_costcenter)
        REFERENCES pems_cost_center (sap_costcenter)
);

CREATE TABLE IF NOT EXISTS pems_load_feeder_map (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    load_id         INT NOT NULL,
    device_id       VARCHAR(6)  NOT NULL,
    feeder_id       SMALLINT    NOT NULL,
    sign            SMALLINT    NOT NULL DEFAULT 1,
    coefficient     NUMERIC(6,3) NOT NULL DEFAULT 1.000,
    effective_from  DATE        NOT NULL DEFAULT DATE '2000-01-01',
    effective_to    DATE,
    is_confirmed    BOOLEAN     NOT NULL DEFAULT false,
    match_score     NUMERIC(5,2),
    notes           VARCHAR(255),
    created_at      TIMESTAMP   NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP   NOT NULL DEFAULT now(),
    CONSTRAINT fk_lfm_load  FOREIGN KEY (load_id) REFERENCES pems_load (id),
    CONSTRAINT fk_lfm_meter FOREIGN KEY (device_id, feeder_id)
        REFERENCES pems_meter (device_id, feeder_id),
    CONSTRAINT uq_lfm UNIQUE (load_id, device_id, feeder_id, effective_from)
);

CREATE TABLE IF NOT EXISTS pems_tariff (
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(60),
    tariff_order_ref    VARCHAR(120),
    voltage_class       VARCHAR(10)  NOT NULL DEFAULT 'EHT',
    consumer_category   VARCHAR(40)  NOT NULL DEFAULT 'Heavy Industry',
    effective_from      DATE         NOT NULL,
    effective_to        DATE,
    status              VARCHAR(10)  NOT NULL DEFAULT 'active',
    slab_lf_low_rate    NUMERIC(9,4),
    slab_lf_high_rate   NUMERIC(9,4),
    lf_threshold_pct    NUMERIC(5,2)  NOT NULL DEFAULT 60.00,
    demand_charge       NUMERIC(9,2),
    electricity_duty_pct NUMERIC(5,2) NOT NULL DEFAULT 9.00,
    meter_rent          NUMERIC(9,2)  NOT NULL DEFAULT 2000,
    customer_service_charge NUMERIC(9,2) NOT NULL DEFAULT 700,
    colony_rate         NUMERIC(9,4),
    tod_rates_json      JSONB,
    pf_bands_json       JSONB,
    rebates_json        JSONB,
    extras_json         JSONB,
    notes               VARCHAR(255),
    created_at          TIMESTAMP NOT NULL DEFAULT now(),
    updated_at          TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT uq_tariff UNIQUE (voltage_class, consumer_category, effective_from)
);

CREATE TABLE IF NOT EXISTS pems_config (
    cfg_key     VARCHAR(60) PRIMARY KEY,
    cfg_value   VARCHAR(255) NOT NULL,
    data_type   VARCHAR(15)  NOT NULL DEFAULT 'string',
    description VARCHAR(255),
    updated_at  TIMESTAMP NOT NULL DEFAULT now()
);

-- =========================================================================
-- TRANSACTIONS & COMPUTED
-- =========================================================================
CREATE TABLE IF NOT EXISTS pems_meter_snapshot (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id       VARCHAR(6)  NOT NULL,
    feeder_id       SMALLINT    NOT NULL,
    period_start    TIMESTAMP   NOT NULL,
    period_end      TIMESTAMP   NOT NULL,
    kwh_initial     NUMERIC(19,2),
    kwh_final       NUMERIC(19,2),
    kvah_initial    NUMERIC(19,2),
    kvah_final      NUMERIC(19,2),
    kwh_delta       NUMERIC(19,2),
    kvah_delta      NUMERIC(19,2),
    had_reset       BOOLEAN     NOT NULL DEFAULT false,
    created_at      TIMESTAMP   NOT NULL DEFAULT now(),
    CONSTRAINT uq_snap UNIQUE (device_id, feeder_id, period_start, period_end)
);

CREATE TABLE IF NOT EXISTS pems_daily_consumption (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consumption_date DATE       NOT NULL,
    load_id          INT,
    sap_costcenter   VARCHAR(20),
    kwh              NUMERIC(19,3),
    kvah             NUMERIC(19,3),
    source           VARCHAR(20) NOT NULL DEFAULT 'computed',
    created_at       TIMESTAMP   NOT NULL DEFAULT now(),
    CONSTRAINT fk_dc_load FOREIGN KEY (load_id) REFERENCES pems_load (id),
    CONSTRAINT uq_dc UNIQUE (consumption_date, load_id)
);

CREATE TABLE IF NOT EXISTS pems_energy_balance (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    balance_month   CHAR(7) NOT NULL,
    grid_mwh        NUMERIC(19,4),
    grid_mvah       NUMERIC(19,4),
    furnace_mwh     NUMERIC(19,4),
    auxiliary_mwh   NUMERIC(19,4),
    detail_json     JSONB,
    created_at      TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT uq_bal UNIQUE (balance_month)
);

CREATE TABLE IF NOT EXISTS pems_sap_posting (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    posting_date    DATE         NOT NULL,
    sap_costcenter  VARCHAR(20)  NOT NULL,
    costcenter_desc VARCHAR(100),
    consumption     NUMERIC(19,3) NOT NULL,
    unit_rate       NUMERIC(12,4),
    amount          NUMERIC(19,2),
    status          VARCHAR(12)  NOT NULL DEFAULT 'pending',
    sap_doc_no      VARCHAR(30),
    request_json    JSONB,
    response_json   JSONB,
    error_msg       VARCHAR(500),
    posted_at       TIMESTAMP,
    posted_by       VARCHAR(80),
    created_at      TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT uq_post UNIQUE (posting_date, sap_costcenter)
);

CREATE TABLE IF NOT EXISTS pems_bill_actual (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_month      CHAR(7) NOT NULL,
    consumer_ac     VARCHAR(20),
    bill_no         VARCHAR(40),
    contract_demand_kva INT,
    billable_demand_kva NUMERIC(12,2),
    power_factor    NUMERIC(6,4),
    load_factor_pct NUMERIC(6,2),
    kwh_total       NUMERIC(19,2),
    kvah_total      NUMERIC(19,2),
    energy_charge   NUMERIC(19,2),
    demand_charge   NUMERIC(19,2),
    tod_charge      NUMERIC(19,2),
    pf_charge       NUMERIC(19,2),
    electricity_duty NUMERIC(19,2),
    dps             NUMERIC(19,2),
    net_payable     NUMERIC(19,2),
    detail_json     JSONB,
    CONSTRAINT uq_bill UNIQUE (bill_month)
);

CREATE TABLE IF NOT EXISTS pems_bill_recon (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_month      CHAR(7) NOT NULL,
    component       VARCHAR(60) NOT NULL,
    computed_value  NUMERIC(19,2),
    actual_value    NUMERIC(19,2),
    variance        NUMERIC(19,2),
    variance_pct    NUMERIC(9,4),
    created_at      TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT uq_recon UNIQUE (bill_month, component)
);

CREATE TABLE IF NOT EXISTS pems_audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor       VARCHAR(80),
    action      VARCHAR(60)  NOT NULL,
    entity      VARCHAR(60),
    entity_id   VARCHAR(60),
    detail_json JSONB,
    created_at  TIMESTAMP NOT NULL DEFAULT now()
);

-- 15-minute rollup of the raw meter data (rebuilt in Postgres by the app scheduler).
CREATE TABLE IF NOT EXISTS pems_meter_15min (
    device_id   VARCHAR(6)  NOT NULL,
    feeder_id   SMALLINT    NOT NULL,
    block_start TIMESTAMP   NOT NULL,
    avg_kw      NUMERIC(12,2),
    avg_kva     NUMERIC(12,2),
    max_kw      NUMERIC(12,2),
    max_kva     NUMERIC(12,2),
    kwh         NUMERIC(19,3),
    kvah        NUMERIC(19,3),
    samples     INT NOT NULL DEFAULT 0,
    PRIMARY KEY (device_id, feeder_id, block_start)
);
CREATE INDEX IF NOT EXISTS idx_15min_block        ON pems_meter_15min (block_start);
CREATE INDEX IF NOT EXISTS idx_15min_feeder_block ON pems_meter_15min (device_id, feeder_id, block_start);

CREATE TABLE IF NOT EXISTS pems_rollup_state (
    rollup_key  VARCHAR(40) PRIMARY KEY,
    last_block  TIMESTAMP,
    updated_at  TIMESTAMP NOT NULL DEFAULT now()
);

-- Date-effective operational constants.
CREATE TABLE IF NOT EXISTS pems_constant (
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ckey           VARCHAR(64)  NOT NULL,
    label          VARCHAR(120) NOT NULL,
    category       VARCHAR(40)  NOT NULL DEFAULT 'General',
    unit           VARCHAR(24),
    cvalue         NUMERIC(18,6) NOT NULL,
    effective_from DATE         NOT NULL,
    note           VARCHAR(255),
    updated_by     VARCHAR(80),
    updated_at     TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT uq_key_from UNIQUE (ckey, effective_from)
);
CREATE INDEX IF NOT EXISTS idx_const_key_date ON pems_constant (ckey, effective_from);

-- Configuration change log (System Settings edits).
CREATE TABLE IF NOT EXISTS pems_audit (
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity         VARCHAR(24)  NOT NULL,
    entity_key     VARCHAR(80)  NOT NULL,
    action         VARCHAR(16)  NOT NULL,
    detail         VARCHAR(500),
    effective_from DATE,
    changed_by     VARCHAR(80),
    changed_at     TIMESTAMP    NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_audit_changed_at ON pems_audit (changed_at);
CREATE INDEX IF NOT EXISTS idx_audit_entity     ON pems_audit (entity, entity_key);

-- Per-meter, date-effective multiplication factors.
CREATE TABLE IF NOT EXISTS pems_meter_factor (
    device_id      VARCHAR(6)   NOT NULL,
    feeder_id      SMALLINT     NOT NULL,
    effective_from DATE         NOT NULL DEFAULT DATE '2026-04-01',
    mult_factor    NUMERIC(9,6) NOT NULL,
    note           VARCHAR(255),
    updated_by     VARCHAR(80),
    updated_at     TIMESTAMP    NOT NULL DEFAULT now(),
    PRIMARY KEY (device_id, feeder_id, effective_from)
);

-- PEMS access roles (admin | manager | viewer).
CREATE TABLE IF NOT EXISTS pems_user_role (
    emp_id      VARCHAR(10)  NOT NULL PRIMARY KEY,
    role        VARCHAR(16)  NOT NULL DEFAULT 'viewer',
    granted_by  VARCHAR(80),
    updated_at  TIMESTAMP    NOT NULL DEFAULT now()
);

-- updated_at triggers on every table that carries the column ------------------
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'pems_cost_center','pems_load','pems_load_feeder_map','pems_tariff',
    'pems_config','pems_constant','pems_meter_factor','pems_user_role','pems_rollup_state'
  ] LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS trg_%1$s_updated ON pems.%1$s', t);
    EXECUTE format('CREATE TRIGGER trg_%1$s_updated BEFORE UPDATE ON pems.%1$s '
                   'FOR EACH ROW EXECUTE FUNCTION pems.set_updated_at()', t);
  END LOOP;
END $$;
