"""Server-side XLSX generation for MIS reports (100% digitalization).

energy_master_xlsx() reproduces the layout of the manual "Energy Master" workbook from a
computed accounting balance, so the sheet is generated by the system instead of by hand.
"""
from __future__ import annotations

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side

_HEAD = Font(bold=True, size=13, color="FFFFFF")
_SECTION = Font(bold=True, color="FFFFFF")
_BOLD = Font(bold=True)
_FILL_HEAD = PatternFill("solid", fgColor="1F5FBF")
_FILL_SECTION = PatternFill("solid", fgColor="2C3E56")
_FILL_TOTAL = PatternFill("solid", fgColor="E8EEF7")
_thin = Side(style="thin", color="D0D6DE")
_BORDER = Border(left=_thin, right=_thin, top=_thin, bottom=_thin)
_RIGHT = Alignment(horizontal="right")
_CENTER = Alignment(horizontal="center")


def energy_master_xlsx(d: dict) -> Workbook:
    wb = Workbook()
    ws = wb.active
    ws.title = f"Energy Master {d['month']}"
    ws.column_dimensions["A"].width = 34
    ws.column_dimensions["B"].width = 16
    ws.column_dimensions["C"].width = 18
    ws.column_dimensions["D"].width = 12

    r = 1
    ws.merge_cells(f"A{r}:D{r}")
    c = ws[f"A{r}"]; c.value = "ENERGY CONSUMPTION REPORT — Balasore Alloys Ltd"
    c.font = _HEAD; c.fill = _FILL_HEAD; c.alignment = _CENTER
    ws.row_dimensions[r].height = 22
    r += 1
    p = d.get("period", {})
    ws.merge_cells(f"A{r}:D{r}")
    ws[f"A{r}"] = (f"Month: {d['month']}   |   {p.get('start','')[:10]} to {p.get('end','')[:10]}"
                   f"   |   {'Complete' if p.get('complete') else 'Month-to-date'}")
    ws[f"A{r}"].alignment = _CENTER
    r += 2

    def section(title: str):
        nonlocal r
        ws.merge_cells(f"A{r}:D{r}")
        cell = ws[f"A{r}"]; cell.value = title; cell.font = _SECTION; cell.fill = _FILL_SECTION
        r += 1

    def header():
        nonlocal r
        for col, val in zip("ABCD", ["Description", "Energy (MWh)", "Cost Center", "Status"]):
            cell = ws[f"{col}{r}"]; cell.value = val; cell.font = _BOLD; cell.border = _BORDER
        r += 1

    def line(name, mwh, cc="", status="", bold=False, fill=None):
        nonlocal r
        ws[f"A{r}"] = name
        ws[f"B{r}"] = round(mwh, 3) if mwh is not None else None
        ws[f"B{r}"].alignment = _RIGHT; ws[f"B{r}"].number_format = "#,##0.000"
        ws[f"C{r}"] = cc; ws[f"C{r}"].alignment = _CENTER
        ws[f"D{r}"] = status; ws[f"D{r}"].alignment = _CENTER
        for col in "ABCD":
            ws[f"{col}{r}"].border = _BORDER
            if bold: ws[f"{col}{r}"].font = _BOLD
            if fill: ws[f"{col}{r}"].fill = fill
        r += 1

    section("GRID (INCOMER)")
    header()
    line("Total Power Consumption (Grid)", d["grid_mwh"], "", "", bold=True, fill=_FILL_TOTAL)
    r += 1

    section("FURNACES")
    header()
    for f in d["furnaces"]:
        line(f["load_name"], f["mwh"], f["sap_costcenter"] or "",
             "Confirmed" if f["confirmed"] else "Suggested")
    line("Total Furnace Power", d["furnace_total_mwh"], "", "", bold=True, fill=_FILL_TOTAL)
    r += 1

    section("AUXILIARY (Grid − Furnaces)")
    header()
    line("Total Auxiliary Power", d["auxiliary_mwh"], "", "", bold=True, fill=_FILL_TOTAL)
    r += 1

    section("INDIVIDUAL LOADS")
    header()
    for l in d["individual_loads"]:
        line(l["load_name"], l["mwh"], l["sap_costcenter"] or "",
             "Confirmed" if l["confirmed"] else "Suggested")
    line("Miscellaneous + Line loss", d["miscellaneous_mwh"], "", "(balancing)")
    r += 1

    section("COST CENTER SUMMARY")
    header()
    for cc in d["cost_centers"]:
        line(cc["description"] or cc["sap_costcenter"] or "Unallocated", cc["mwh"],
             cc["sap_costcenter"] or "", "")

    r += 1
    ws.merge_cells(f"A{r}:D{r}")
    ws[f"A{r}"] = f"Method: {d.get('method','')}"
    ws[f"A{r}"].font = Font(italic=True, size=9, color="7B8694")
    return wb
